<?php

namespace Ads\ProcessBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertisementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisementsRepository extends EntityRepository
{
}
